# Data for code analysis
Copy and validate users uploads before analysis

# Check uploads

In [17]:
import os
import shutil
import pandas as pd

activity_csv_path = "../../data/database/activity.csv"
if not os.path.exists(activity_csv_path):
    raise FileNotFoundError(f"Le fichier de données de l'expérimentation {activity_csv_path} n'existe pas.")

users_csv_path = "../../generated/database/users.csv"
if not os.path.exists(users_csv_path):
    raise FileNotFoundError(f"Le fichier {users_csv_path} n'existe pas. Exécutez le notebook 'notebooks/arrange data/Database data.ipynb' pour le générer.")

users = pd.read_csv(users_csv_path)[["user", "created_at", "last_update", "group"]]
users['created_at'] = pd.to_datetime(users['created_at'], utc=True).dt.tz_convert("Europe/Brussels")
users['last_update'] = pd.to_datetime(users['last_update'], utc=True).dt.tz_convert("Europe/Brussels")

users

,user,created_at,last_update,group
0,b0ce21ef-0c91-4be3-8aed-9bd1062ce0bf,2025-04-17 11:36:13.931764+02:00,2025-04-17 11:36:13.931764+02:00,NaN
1,1d20c70c-aa71-49ff-abf5-6013870a28f8,2025-04-17 09:09:34.466356+02:00,2025-04-17 10:15:15.091865+02:00,A
2,d65a1736-2d35-44e8-bf24-d1fd976c741f,2025-04-17 09:03:46.194595+02:00,2025-04-17 10:01:42.338618+02:00,A
3,223bf16c-aaad-404f-8a47-61f3ced741e4,2025-04-17 09:02:43.126709+02:00,2025-04-17 10:10:23.313570+02:00,A
4,7b25b9f2-5d8e-401e-aefa-ac31e94575d1,2025-04-17 09:03:08.265702+02:00,2025-04-17 10:00:45.647904+02:00,B
5,b39dc415-9bb6-4d5d-a8f9-30fd61f6a594,2025-04-17 09:03:01.841544+02:00,2025-04-17 10:06:40.220746+02:00,A
6,11555248-3f01-4d1c-9a71-ef7caf9150fa,2025-04-17 09:11:51.549595+02:00,2025-04-17 09:22:39.426644+02:00,B
7,1fc23e66-121e-450a-86ba-d109bc64b9bb,2025-04-17 09:29:20.120754+02:00,2025-04-17 09:29:20.120754+02:00,NaN
8,2b2965f7-5d66-4569-802b-27c84aa69bff,2025-04-17 09:02:34.502892+02:00,2025-04-17 09:22:44.881721+02:00,B
9,eed81e54-2343-44af-ab2f-cd062db7e11a,2025-04-17 09:02:32.078794+02:00,2025-04-17 09:24:08.305693+02:00,B
10,a980dad5-6719-44ac-a40e-4c0b35663e68,2025-04-17 09:03:18.189337+02:00,2025-04-17 09:29:46.502182+02:00,A
11,49ca41e9-25d5-4cf1-8157-94e27dfa3987,2025-04-17 09:02:58.430046+02:00,2025-04-17 09:30:38.433413+02:00,A
12,ff65b446-d728-4f12-98a8-c63529c589ba,2025-04-17 09:09:13.035705+02:00,2025-04-17 09:59:42.521138+02:00,A
13,afb0f9dc-6acf-48cd-a0e1-032f5df9366f,2025-04-17 09:03:07.158631+02:00,2025-04-17 09:22:58.240005+02:00,B
14,69f381b2-d619-4968-9db9-ec0e3b10f850,2025-04-17 09:02:33.211946+02:00,2025-04-17 09:28:00.647588+02:00,B
15,4d14cb87-b95e-4575-8823-f951391a3e6a,2025-04-17 09:02:34.156243+02:00,2025-04-17 09:23:00.687644+02:00,B
16,dbcd3c5d-5f82-4c84-88cc-8a101893e23c,2025-04-17 09:03:38.219653+02:00,2025-04-17 10:07:24.675910+02:00,A
17,465777bf-b8f8-4dbe-b99e-7e1c208be8dc,2025-04-17 09:03:47.092044+02:00,2025-04-17 09:23:09.433316+02:00,B
18,88a83dd8-0ea0-41ad-93ca-d397d796fb37,2025-04-17 09:02:34.615072+02:00,2025-04-17 09:43:27.582671+02:00,B
19,64330b4a-8b12-4c91-9b78-5942c1b9325f,2025-04-17 09:22:22.063502+02:00,2025-04-17 09:44:15.755475+02:00,B
20,72b5701e-d26c-49cb-a91b-6a3249246495,2025-04-17 09:44:55.448631+02:00,2025-04-17 09:44:55.448631+02:00,B
21,de176a06-3fc9-4325-8c81-f131f193c1c4,2025-04-17 09:02:33.106916+02:00,2025-04-17 10:02:56.430111+02:00,A
22,9af94b6b-259c-4799-8c79-5960311627bf,2025-04-17 09:05:48.107934+02:00,2025-04-17 09:24:40.808968+02:00,A
23,f9ec833e-db4f-49b9-9b14-08298cbb4425,2025-04-17 09:02:32.181151+02:00,2025-04-17 09:33:40.465524+02:00,B
24,f08453ce-2b6e-40e4-a0b4-0c37218608fa,2025-04-17 09:02:59.461322+02:00,2025-04-17 10:04:21.118507+02:00,A
25,674eeeb6-2534-419d-8965-63e4400f60c4,2025-04-17 09:02:52.034965+02:00,2025-04-17 10:06:18.206590+02:00,A
26,0d271530-be17-4538-bf04-dde3c6069b5f,2025-04-17 09:02:57.746025+02:00,2025-04-17 10:12:30.330211+02:00,A
27,db05d465-5823-4bdd-b3b8-55eb42642552,2025-04-17 09:02:50.088437+02:00,2025-04-17 09:25:30.381074+02:00,A
28,465f4b36-5fbb-415c-8e64-2401771ce91d,2025-04-17 09:21:22.026098+02:00,2025-04-17 09:25:37.899686+02:00,B
29,7234f6dc-a316-4576-8453-6e10d7cf1c3d,2025-04-17 09:02:56.840758+02:00,2025-04-17 10:04:28.202281+02:00,A
30,d5082901-d846-4794-82af-2c7db8d50788,2025-04-17 09:02:33.352072+02:00,2025-04-17 09:25:38.167092+02:00,B
31,60716858-6fcb-4953-88e3-12a51b3c7c47,2025-04-17 09:02:34.497612+02:00,2025-04-17 09:34:46.034695+02:00,B
32,ca639c6f-a4d1-464c-9b8b-0351617a59b5,2025-04-17 09:02:31.843815+02:00,2025-04-17 09:23:55.550971+02:00,B
33,fb270a09-6a45-4eae-8f9a-3c808faec3ee,2025-04-17 09:03:18.880723+02:00,2025-04-17 09:36:12.760279+02:00,B
34,a7c1124d-d4fc-4fc7-bb6f-b73e2f1b7fdd,2025-04-17 09:02:51.248878+02:00,2025-04-17 10:06:23.380871+02:00,A
35,70e85b5e-92d4-498a-9079-ba881f5b3b82,2025-04-17 09:02:31.374147+02:00,2025-04-17 09:24:04.313230+02:00,B
36,caadbaac-e919-4b9b-b3a5-9d074d40493c,2025-04-17 09:02:51.188801+02:00,2025-04-17 10:08:27.900674+02:00,A
37,70c71a91-06a1-4bf4-8e56-f4327b1c8b3f,2025-04-17 09:03:34.549003+02:00,2025-04-17 10:06:30.001053+02:00,A
38,1f06f352-91b6-4373-87ed-5a5070723efb,2025-04-17 09:02:52.703695+02:00,2025-04-17 10:06:34.058738+02:00,A
39,3e58c347-cdf0-4139-93e0-1adf144753c4,2025-04-17 09:08:48.927970+02:00,2025-04-17 10:09:43.845548+02:00,A
40,11b1644a-d11f-45cb-8a40-282a209059c0,2025-04-17 09:02:51.426609+02:00,2025-04-17 10:42:17.994423+02:00,A

In [18]:
uploads_path = "../../data/uploads"
directories = os.listdir(uploads_path)

for user_id in directories:
    child = os.listdir(uploads_path + "/" + user_id)
    uploads_count = len(child)

    users.loc[users["user"] == user_id, "uploads_count"] = uploads_count

    if uploads_count > 2:
        print(f"{user_id} has {uploads_count} directories instead of 2")
        for folder_name in child:
            print(f"\t{folder_name}")
        print("")


users["uploads_count"] = users["uploads_count"].fillna(0)
users["uploads_count"] = users["uploads_count"].astype(int)

1d20c70c-aa71-49ff-abf5-6013870a28f8 has 3 directories instead of 2
	2025-04-17T07-46-46.781Z
	2025-04-17T07-46-49.089Z
	2025-04-17T08-06-49.533Z

3e58c347-cdf0-4139-93e0-1adf144753c4 has 4 directories instead of 2
	2025-04-17T07-30-22.616Z
	2025-04-17T07-42-18.812Z
	2025-04-17T07-51-07.217Z
	2025-04-17T08-06-56.837Z

9af94b6b-259c-4799-8c79-5960311627bf has 4 directories instead of 2
	2025-04-17T07-26-52.491Z
	2025-04-17T08-05-27.514Z
	2025-04-17T08-05-28.156Z
	2025-04-17T08-05-30.026Z

a980dad5-6719-44ac-a40e-4c0b35663e68 has 3 directories instead of 2
	2025-04-17T07-25-08.437Z
	2025-04-17T07-25-10.346Z
	2025-04-17T07-27-08.814Z

f08453ce-2b6e-40e4-a0b4-0c37218608fa has 3 directories instead of 2
	2025-04-17T07-26-22.593Z
	2025-04-17T07-27-40.096Z
	2025-04-17T08-07-41.079Z

# User mismatch send count

In [28]:
activity_df = pd.read_csv(activity_csv_path)[["user"]]
activity_counts = activity_df["user"].value_counts().reset_index()
activity_counts.columns = ["user", "activity_count"]

mismatch_send_df = users[users["uploads_count"] != 2]
mismatch_send_df = mismatch_send_df.merge(activity_counts, on="user", how="left")
mismatch_send_df["activity_count"] = mismatch_send_df["activity_count"].fillna(0)
mismatch_send_df["group"] = mismatch_send_df["group"].fillna("Inconnu")
mismatch_send_df.to_csv("../../generated/database/users_send_mismatch.csv", index=False)
mismatch_send_df

,user,created_at,last_update,group,uploads_count,activity_count
0,b0ce21ef-0c91-4be3-8aed-9bd1062ce0bf,2025-04-17 11:36:13.931764+02:00,2025-04-17 11:36:13.931764+02:00,Inconnu,0,0.0
1,1d20c70c-aa71-49ff-abf5-6013870a28f8,2025-04-17 09:09:34.466356+02:00,2025-04-17 10:15:15.091865+02:00,A,3,3.0
2,11555248-3f01-4d1c-9a71-ef7caf9150fa,2025-04-17 09:11:51.549595+02:00,2025-04-17 09:22:39.426644+02:00,B,1,4.0
3,1fc23e66-121e-450a-86ba-d109bc64b9bb,2025-04-17 09:29:20.120754+02:00,2025-04-17 09:29:20.120754+02:00,Inconnu,0,0.0
4,a980dad5-6719-44ac-a40e-4c0b35663e68,2025-04-17 09:03:18.189337+02:00,2025-04-17 09:29:46.502182+02:00,A,3,24.0
5,ff65b446-d728-4f12-98a8-c63529c589ba,2025-04-17 09:09:13.035705+02:00,2025-04-17 09:59:42.521138+02:00,A,0,13.0
6,afb0f9dc-6acf-48cd-a0e1-032f5df9366f,2025-04-17 09:03:07.158631+02:00,2025-04-17 09:22:58.240005+02:00,B,0,13.0
7,72b5701e-d26c-49cb-a91b-6a3249246495,2025-04-17 09:44:55.448631+02:00,2025-04-17 09:44:55.448631+02:00,B,0,21.0
8,9af94b6b-259c-4799-8c79-5960311627bf,2025-04-17 09:05:48.107934+02:00,2025-04-17 09:24:40.808968+02:00,A,4,13.0
9,f08453ce-2b6e-40e4-a0b4-0c37218608fa,2025-04-17 09:02:59.461322+02:00,2025-04-17 10:04:21.118507+02:00,A,3,14.0
10,db05d465-5823-4bdd-b3b8-55eb42642552,2025-04-17 09:02:50.088437+02:00,2025-04-17 09:25:30.381074+02:00,A,0,11.0
11,7234f6dc-a316-4576-8453-6e10d7cf1c3d,2025-04-17 09:02:56.840758+02:00,2025-04-17 10:04:28.202281+02:00,A,0,47.0
12,fb270a09-6a45-4eae-8f9a-3c808faec3ee,2025-04-17 09:03:18.880723+02:00,2025-04-17 09:36:12.760279+02:00,B,0,81.0
13,3e58c347-cdf0-4139-93e0-1adf144753c4,2025-04-17 09:08:48.927970+02:00,2025-04-17 10:09:43.845548+02:00,A,4,21.0

# Users with less than 2 uploads

In [29]:
less_than_2 = mismatch_send_df[mismatch_send_df["uploads_count"] < 2]
less_than_2 = less_than_2[["user", "uploads_count", "activity_count", "group"]]
less_than_2.to_csv("../../generated/database/users_send_mismatch_less_2.csv", index=False)

# Copy & clean data

In [20]:
timing_path = "../../generated/database/timing.csv"
if not os.path.exists(timing_path):
    raise FileNotFoundError("Le fichier timing.csv n'existe pas. Exécutez le notebook 'notebooks/arrange data/Database data.ipynb' pour le générer.")

timing_df = pd.read_csv(timing_path)

uploads_path = "../../data/uploads"
directories = os.listdir(uploads_path)

out_uploads_path = "../../generated/uploads"

if os.path.exists(out_uploads_path):
    print(f"Deleting {out_uploads_path}\n")
    shutil.rmtree(out_uploads_path)

os.makedirs(out_uploads_path)

for user_id in directories:
    user_uploads_path = uploads_path + "/" + user_id

    child = os.listdir(user_uploads_path)
    uploads_count = len(child)

    if uploads_count < 2:
        print(f"Ignoring {user_id} - {uploads_count} uploaded project(s)")
        continue

    out_user_uploads_path = out_uploads_path + "/" + user_id

    os.makedirs(out_user_uploads_path)

    group = users[users['user'] == user_id]['group'].values[0]

    group_timings = timing_df[timing_df['group'] == group].copy()
    group_timings.loc[:, 'start'] = pd.to_datetime(group_timings['start'])
    group_timings.loc[:, 'end'] = pd.to_datetime(group_timings['end'])

    child.sort()
    found_files = []

    for i, session in group_timings.iterrows():
        session_start = session['start']
        session_end = session['end']

        first_matching_dir = None
        for dir_name in child:
            dir_time = pd.to_datetime(dir_name.split('.')[0], format='%Y-%m-%dT%H-%M-%S', utc=True).tz_convert("Europe/Brussels")

            if i == 0:  # First session
                next_session_end = group_timings.iloc[1]['end']
                if dir_time <= next_session_end and first_matching_dir is None:
                    first_matching_dir = dir_name
            else:  # Second session
                if dir_time >= session_end and first_matching_dir is None:
                    first_matching_dir = dir_name
                    break

        if first_matching_dir:
            found_files.append(first_matching_dir)

    if len(found_files) != 2:
        os.rmdir(out_user_uploads_path)
        print(f"Ignoring {user_id} - found only {len(found_files)} uploaded project(s) with valid timing")
    else:
        #print(f"{user_id} - group {group}")
        for path in found_files:
            #print("\t" + path)
            shutil.copytree(f"{user_uploads_path}/{path}", f"{out_user_uploads_path}/{path}", dirs_exist_ok=True)

Deleting ../../generated/uploads

Ignoring 11555248-3f01-4d1c-9a71-ef7caf9150fa - 1 uploaded project(s)
Ignoring 465f4b36-5fbb-415c-8e64-2401771ce91d - found only 1 uploaded project(s) with valid timing
Ignoring 49ca41e9-25d5-4cf1-8157-94e27dfa3987 - found only 1 uploaded project(s) with valid timing
Ignoring 9af94b6b-259c-4799-8c79-5960311627bf - found only 1 uploaded project(s) with valid timing
Ignoring a980dad5-6719-44ac-a40e-4c0b35663e68 - found only 1 uploaded project(s) with valid timing
Ignoring de176a06-3fc9-4325-8c81-f131f193c1c4 - found only 1 uploaded project(s) with valid timing

# Verified data

In [21]:
directories = os.listdir(out_uploads_path)
invalid_directories = 0

for user_id in directories:
    child = os.listdir(out_uploads_path + "/" + user_id)
    uploads_count = len(child)

    if uploads_count != 2:
        invalid_directories = invalid_directories + 1
        print(f"{user_id} has {uploads_count} directories instead of 2")
        for folder_name in child:
            print(f"\t{folder_name}")
        print("")


if invalid_directories == 0:
    print("All users have 2 directories")

All users have 2 directories

In [22]:
print(out_uploads_path)
directories = os.listdir(out_uploads_path)

for user_id in directories:
    child = os.listdir(out_uploads_path + "/" + user_id)
    child.sort()

    time1 = pd.to_datetime(child[0].split('.')[0], format='%Y-%m-%dT%H-%M-%S', utc=True).tz_convert("Europe/Brussels")
    time2 = pd.to_datetime(child[1].split('.')[0], format='%Y-%m-%dT%H-%M-%S', utc=True).tz_convert("Europe/Brussels")

    time_diff = time2 - time1
    print(f"User {user_id}: Time difference between uploads = {time_diff}")

../../generated/uploads
User 0d271530-be17-4538-bf04-dde3c6069b5f: Time difference between uploads = 0 days 00:41:48
User 11b1644a-d11f-45cb-8a40-282a209059c0: Time difference between uploads = 0 days 00:41:13
User 1d20c70c-aa71-49ff-abf5-6013870a28f8: Time difference between uploads = 0 days 00:20:03
User 1f06f352-91b6-4373-87ed-5a5070723efb: Time difference between uploads = 0 days 00:40:38
User 223bf16c-aaad-404f-8a47-61f3ced741e4: Time difference between uploads = 0 days 00:40:55
User 2b2965f7-5d66-4569-802b-27c84aa69bff: Time difference between uploads = 0 days 00:40:11
User 3e58c347-cdf0-4139-93e0-1adf144753c4: Time difference between uploads = 0 days 00:36:34
User 465777bf-b8f8-4dbe-b99e-7e1c208be8dc: Time difference between uploads = 0 days 00:40:46
User 4d14cb87-b95e-4575-8823-f951391a3e6a: Time difference between uploads = 0 days 00:39:03
User 60716858-6fcb-4953-88e3-12a51b3c7c47: Time difference between uploads = 0 days 00:41:01
User 64330b4a-8b12-4c91-9b78-5942c1b9325f: Time difference between uploads = 0 days 00:36:02
User 674eeeb6-2534-419d-8965-63e4400f60c4: Time difference between uploads = 0 days 00:38:42
User 69f381b2-d619-4968-9db9-ec0e3b10f850: Time difference between uploads = 0 days 00:36:49
User 70c71a91-06a1-4bf4-8e56-f4327b1c8b3f: Time difference between uploads = 0 days 00:40:59
User 70e85b5e-92d4-498a-9079-ba881f5b3b82: Time difference between uploads = 0 days 00:41:08
User 7b25b9f2-5d8e-401e-aefa-ac31e94575d1: Time difference between uploads = 0 days 00:40:52
User 88a83dd8-0ea0-41ad-93ca-d397d796fb37: Time difference between uploads = 0 days 00:40:42
User a7c1124d-d4fc-4fc7-bb6f-b73e2f1b7fdd: Time difference between uploads = 0 days 00:37:37
User b39dc415-9bb6-4d5d-a8f9-30fd61f6a594: Time difference between uploads = 0 days 00:40:58
User ca639c6f-a4d1-464c-9b8b-0351617a59b5: Time difference between uploads = 0 days 00:40:29
User caadbaac-e919-4b9b-b3a5-9d074d40493c: Time difference between uploads = 0 days 00:41:20
User d5082901-d846-4794-82af-2c7db8d50788: Time difference between uploads = 0 days 00:39:27
User d65a1736-2d35-44e8-bf24-d1fd976c741f: Time difference between uploads = 0 days 00:14:35
User dbcd3c5d-5f82-4c84-88cc-8a101893e23c: Time difference between uploads = 0 days 00:49:04
User eed81e54-2343-44af-ab2f-cd062db7e11a: Time difference between uploads = 0 days 00:40:58
User f08453ce-2b6e-40e4-a0b4-0c37218608fa: Time difference between uploads = 0 days 00:41:19
User f9ec833e-db4f-49b9-9b14-08298cbb4425: Time difference between uploads = 0 days 00:40:00